### PR TITLE
Fixed losing a notification on Android

### PR DESCRIPTION
**Pull request by dki1110**
I found losing a notification/indication on Android.
The notification/indication occurred right after calling writeDescriptor before calling setCharacteristicNotification(chara, true).
I changed order of calling these to fix.

### CODE REVIEW

**Comment by randdusing** [comment]
This seems like a risky change. Are you sure this isn't device / peripheral specific? What devices did you test it on?

**Comment by dki1110** [comment]
Thank you for your reply.

I tested following devices.  
Both, on DeviceA and B, this issue occurred.
I did effect confirmation (result is OK). But, I did not regression test.

*Central*
Nexus 5X (Android 8.1.0)

*Peripheral*
- DeviceA: support Blood Pressure Service
- DeviceB: support Pulse Oximeter Service



I captured Bluetooth HCI snoop log.  
I saw that time from write response (for descriptor) to send indication is very short. The time is about 0.000182 sec.

Also, I coded test code by android native, and checked it with these devices.

*no problem*
```java
@Override
public void onServicesDiscovered(BluetoothGatt gatt, int status) {
  ...
  gatt.setCharacteristicNotification(characteristic, true);

  BluetoothGattDescriptor descriptor = characteristic.getDescriptor(UUID.fromString(UUID_NOTIFY));
  descriptor.setValue(BluetoothGattDescriptor.ENABLE_INDICATION_VALUE); 

  // Enable onCharacteristicChanged callback 

  gatt.writeDescriptor(descriptor);

  // Perhaps, after very short time, a indication is occurring
}
```

*This issue occurred*
```java
@Override
public void onServicesDiscovered(BluetoothGatt gatt, int status) {
  ...
  BluetoothGattDescriptor descriptor = characteristic.getDescriptor(UUID.fromString(UUID_NOTIFY));
  descriptor.setValue(BluetoothGattDescriptor.ENABLE_INDICATION_VALUE);
  gatt.writeDescriptor(descriptor);

  // Perhaps, after very short time, a indication is occurring. 
  // But, onCharacteristicChanged callback is not enabled.
}

@Override
public void onDescriptorWrite(BluetoothGatt gatt, BluetoothGattDescriptor descriptor, int status) {
    gatt.setCharacteristicNotification(descriptor.getCharacteristic(), true);

    // Enable onCharacteristicChanged callback. 
    // But, a indication already occurred.
}
```

**Comment by codecat** [comment]
I'm not sure I understand what exactly this change does, but I just tested this and it has fixed all of the problems I was having with notifier characteristics! I hope this gets merged.

Thanks for the pull request! 👍

**Comment by codecat** [comment]
More device info from my end, I tested it on several Android central devices where I had the problem, where with this change it's all fixed now.

Centrals:
* OnePlus 5 (Android 7.1.1)
* OnePlus 2 (Android 10.0)

And the peripheral on a Raspberry Pi, running [a fork of Paypal's Gatt](https://github.com/ans-net/gatt).

**Comment by randdusing** [comment]
Thanks @dki1110 and @codecat for confirming. I was hoping a few people would chime in and confirm no issues with existing things that already worked.

Perhaps I can just bump the major version and see if any issues are raised.

**Comment by codecat** [comment]
Thanks for merging!

**Pull request merged**
