### PR TITLE
Master

### PR DESCRIPTION
**Pull request by helixhuang**
Add isBonded and bond method (Android Only)

### CODE REVIEW

**Comment by randdusing** [comment]
Great work Helix! Are you able to make the following changes:

- Make the bonded callback at the device level so multiple bondings could theoretically be possible.
- Add an unsupported method for iOS

If not, I'll merge it after I do some quick verifications and will make those changes at a later time.

**Comment by randdusing** [comment]
An unbond method would be nice too

**Comment by helixhuang** [comment]
randdusing , I will do these works  :)

**Comment by randdusing** [comment]
Hi Helix,

I've made some modifications to your PR and created a new PR [here](https://github.com/randdusing/cordova-plugin-bluetoothle/pull/306) that I just merged. Thanks again for your help.

Rand

**Pull request merged**
