### PR TITLE
#455 on BT state OFF stopping scan for Android version 6.0.0 or above

### PR DESCRIPTION
**Pull request by swetha-thoomoju**
I tried using the same code as in stopScanAction. I don't know why but the app crashes for LOLLIPOP 5.1.1.
So I changed the check for marshmello (M)

### CODE REVIEW

**Comment by randdusing** [comment]
It should work for both with the same code in stopScan. What type of error did you see?

**Comment by swetha-thoomoju** [comment]
## Without Fix:
Turn of BT while scanning is in process then try scanning  
Start Scan Success : {"status":"scanStarted"}  _But right after that_
Start Scan Error : {"error":"startScan","message":"Scan already started"} _If I try stoping scan_
Stop Scan Error : {"error":"stopScan","message":"Not scanning"} 
_**I guess the state of gatt and plugin not matching**_

## With code as in stopScanAction
`if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.LOLLIPOP) {
      bluetoothAdapter.stopLeScan(scanCallbackKitKat);
    } else {
      bluetoothAdapter.getBluetoothLeScanner().stopScan(scanCallback);
    }`


**adb logs for 5.1.1**
--------- beginning of crash
E/AndroidRuntime(27992): FATAL EXCEPTION: main
E/AndroidRuntime(27992): Process: com.caribou.wesko, PID: 27992
E/AndroidRuntime(27992): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x14000010 (has extras) } in com.randdusing.bluetoothle.BluetoothLePlugin$1@1fda19bd
E/AndroidRuntime(27992): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:879)
E/AndroidRuntime(27992): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(27992): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27992): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(27992): 	at android.app.ActivityThread.main(ActivityThread.java:5298)
E/AndroidRuntime(27992): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27992): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(27992): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(27992): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(27992): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeScanner.stopScan(android.bluetooth.le.ScanCallback)' on a null object reference
E/AndroidRuntime(27992): 	at com.randdusing.bluetoothle.BluetoothLePlugin$1.onReceive(BluetoothLePlugin.java:2785)
E/AndroidRuntime(27992): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:869)
E/AndroidRuntime(27992): 	... 8 more

**Comment by randdusing** [comment]
Not sure if I really understand the issue. Is this the error you get without any changes to plugin or after you add your changes? What are the exact steps to reproduce and when does it crash?

**Comment by jmesa-sistel** [comment]
@randdusing 
I know it is an old issue, but I have the same problem.
If you disable bluetooth manually then I cannot scan anymore. I have the same problems described by @swetha-thoomoju .
I have tested the patch on Android 10 and it is working fine.
It would be great if you merge this pull request.

**Comment by aivantsov** [comment]
@randdusing Could you please review the PR and give it a go. We need the patch badly.
Thanks in advance.

**Pull request merged**
