### PR TITLE
Add plugin typings

### PR DESCRIPTION
**Pull request by matrosov-nikita**

### CODE REVIEW

**Comment by randdusing** [comment]
I don't use typescript, so not really sure how to validate this. I assume this doesn't affect anyone who doesn't use typescript?

**Comment by vladimir-kotikov** [comment]
Hey, @randdusing 

There is no really good way to validate this apart from manually going through all definitions and ensuring that all signatures are correct. We could write some tests, just like people in DefinitelyTyped do, probably by taking some existing samples and rewriting them in Typescript and ensuring they compile with these definitions, but these tests wouldn't prove that definitions are correct - just that they compile with the TS code we wrote :)

As for affecting existing JS/TS projects - these definitions definitely wouldn't break any existing JS projects as they'll be just some kind of a source of information for some IDEs (in particular VSCode and Visual Studio) to provide Intellisense.

**Comment by matrosov-nikita** [comment]
@randdusing, see the examples below:

It's a list of available methods:

screenshot2

It's a hint for `connect` signature:

screenshot1

**Comment by randdusing** [comment]
Looks good, thanks for the PR!

**Pull request merged**
